# Generated by Django 5.2.9 on 2025-12-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='certificate_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('data_analysis', 'Data Analysis'), ('dashboard', 'Dashboard'), ('data_visualization', 'Data Visualization'), ('machine_learning', 'Machine Learning'), ('other', 'Other')], default='data_analysis', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='key_achievements',
            field=models.TextField(blank=True, help_text='Bullet points separated by newlines'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='completed', max_length=20),
        ),
    ]
