# Generated by Django 5.2.9 on 2025-12-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_title_certificate_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hero_cta_primary',
            field=models.CharField(default='View My Work', help_text='Primary call-to-action button text', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_cta_secondary',
            field=models.CharField(default='Get In Touch', help_text='Secondary call-to-action button text', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Full description text in hero section (appears with profile picture)'),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_heading',
            field=models.CharField(default='Transforming Data Into Strategic Insights', help_text='Main heading text for hero section', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Short tagline above the main heading', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='show_profile_picture',
            field=models.BooleanField(default=True, help_text='Display profile picture in hero section'),
        ),
    ]
