# Generated by Django 5.2.9 on 2025-12-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about_hero_cta_primary_about_hero_cta_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='footer_copyright_text',
            field=models.CharField(blank=True, help_text='Custom copyright text (leave blank for auto-generated)', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='footer_show_resume_link',
            field=models.BooleanField(default=True, help_text='Display resume download link in footer'),
        ),
        migrations.AddField(
            model_name='about',
            name='footer_show_social_links',
            field=models.BooleanField(default=True, help_text='Display social media links in footer'),
        ),
        migrations.AddField(
            model_name='about',
            name='footer_tagline',
            field=models.CharField(blank=True, default='Turning data into insights', help_text='Footer tagline or motto', max_length=200),
        ),
    ]
