# Generated by Django 4.2.7 on 2025-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='stat_certifications',
            field=models.IntegerField(blank=True, default=None, help_text='Custom count for certifications stat (leave blank to auto-count from database)', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_experience',
            field=models.IntegerField(blank=True, default=None, help_text='Custom count for years of experience (leave blank to auto-count from database)', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_projects',
            field=models.IntegerField(blank=True, default=None, help_text='Custom count for projects stat (leave blank to auto-count from database)', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_skills',
            field=models.IntegerField(blank=True, default=None, help_text='Custom count for skills stat (leave blank to auto-count from database)', null=True),
        ),
    ]
