# Generated by Django 4.2.7 on 2025-12-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about_stat_certifications_about_stat_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='availability_status',
            field=models.BooleanField(default=True, help_text='Toggle availability status on/off'),
        ),
        migrations.AddField(
            model_name='about',
            name='availability_text',
            field=models.CharField(default='Available for projects', help_text='Custom availability status text (e.g., "Available for projects", "Currently busy", "Open to opportunities")', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed project description. Support for HTML and images. You can include HTML tags for formatting.'),
        ),
    ]
