# Generated by Django 4.2.7 on 2025-12-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_about_availability_status_about_availability_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='custom_svg',
            field=models.TextField(blank=True, help_text="Paste custom SVG code here (only used when icon is set to 'Custom SVG')"),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, choices=[('', '-- Select Icon --'), ('python', 'Python'), ('sql', 'SQL'), ('r-lang', 'R Language'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('git', 'Git'), ('terminal', 'Terminal/CLI'), ('code', 'Code/Programming'), ('database', 'Database'), ('api', 'API'), ('excel', 'Excel'), ('tableau', 'Tableau'), ('powerbi', 'Power BI'), ('jupyter', 'Jupyter'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('spark', 'Apache Spark'), ('hadoop', 'Hadoop'), ('chart-bar', 'Bar Chart'), ('chart-line', 'Line Chart'), ('chart-pie', 'Pie Chart'), ('analytics', 'Analytics'), ('dashboard', 'Dashboard'), ('report', 'Report'), ('statistics', 'Statistics'), ('brain', 'AI/Brain'), ('neural-network', 'Neural Network'), ('robot', 'Machine Learning'), ('target', 'Prediction/Target'), ('users', 'Team/Collaboration'), ('communication', 'Communication'), ('lightbulb', 'Problem Solving'), ('clock', 'Time Management'), ('presentation', 'Presentation'), ('leadership', 'Leadership'), ('creative', 'Creativity'), ('detail', 'Attention to Detail'), ('learning', 'Fast Learner'), ('cloud', 'Cloud'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'Google Cloud'), ('server', 'Server'), ('star', 'Star'), ('check', 'Checkmark'), ('bolt', 'Lightning Bolt'), ('cog', 'Settings/Cog'), ('custom', 'Custom SVG')], default='', help_text='Select a predefined icon', max_length=100),
        ),
    ]
