# Generated by Django 4.2.7 on 2025-12-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-end_year', '-start_year'], 'verbose_name_plural': 'Education'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_month',
            field=models.IntegerField(blank=True, help_text='1-12 (optional)', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, help_text='e.g., 2024', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_month',
            field=models.IntegerField(blank=True, help_text='1-12 (optional)', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True, help_text='e.g., 2020', null=True),
        ),
    ]
