# Generated by Django 4.2.7 on 2025-12-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_education_options_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Upload certificate/diploma image (optional)', null=True, upload_to='education_certificates/'),
        ),
    ]
